default: &default
  # configure aqui, o problema pode ser a senha o nome e etc
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: project_survey_api_development

test:
  <<: *default
  database: project_survey_api_test

production:
  <<: *default
  database: project_survey_api_production
  username: project_survey_api
  password: <%= ENV["PROJECT_SURVEY_API_DATABASE_PASSWORD"] %>
